In [68]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [69]:
df = pd.read_csv(
    r"C:\Users\praja\OneDrive\Codes_Project\Data_Science\Machine Learning\EDA\Handling Data\Imputation\Univariate Handling\Titanic.csv",
    usecols=['Age', 'Pclass', 'Fare', 'Survived']
)

df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [70]:
X = df[['Age', 'Pclass', 'Fare']]
y = df['Survived']

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=2)

In [72]:
X_train.head( )

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [76]:
knn = KNNImputer(n_neighbors=5,weights='distance')

X_train_trf = knn.fit_transform(X_train)
X_test_trf = knn.fit_transform(X_test)

In [77]:
pd.DataFrame(X_train_trf, columns=X_train.columns)

           Age  Pclass      Fare
0    40.000000     1.0   27.7208
1     4.000000     3.0   16.7000
2    47.000000     3.0    9.0000
3     9.000000     3.0   31.3875
4    20.000000     3.0    9.8458
..         ...     ...       ...
707  30.000000     3.0    8.6625
708  25.047962     3.0    8.7125
709  71.000000     1.0   49.5042
710  29.530076     1.0  221.7792
711  49.275927     1.0   25.9250

[712 rows x 3 columns]

In [78]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)

y_pred = lr.predict(X_test_trf)

accuracy_score(y_test, y_pred)

0.6983240223463687

In [79]:
# Comparistion with simple Imputer --> Mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2  = si.fit_transform(X_test)

In [80]:
lr = LogisticRegression()

lr.fit(X_train_trf2, y_train)

y_pred1 = lr.predict(X_test_trf2)

accuracy_score(y_test, y_pred1)

0.6927374301675978