# Column Transformer

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('covid_toy.csv')
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [5]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [4]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']), df['has_covid'], test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
55   81  Female  101.0    Mild     Mumbai
41   82    Male    NaN    Mild    Kolkata
73   34    Male   98.0  Strong    Kolkata
14   51    Male  104.0    Mild  Bangalore
33   26  Female   98.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
76   80    Male  100.0    Mild  Bangalore
66   51    Male  104.0    Mild    Kolkata
96   51  Female  101.0  Strong    Kolkata
83   17  Female  104.0    Mild    Kolkata
88    5  Female  100.0    Mild    Kolkata

[80 rows x 5 columns]

In [8]:
from sklearn.compose import  ColumnTransformer

In [11]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(sparse_output=False, drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [12]:
transformer.fit_transform(X_train).shape

(80, 7)

In [13]:
transformer.transform(X_test).shape

(20, 7)